[config]
time_summary = false
default_to_workspace = false

[tasks.install-deps]
command = "cargo"
args = ["install", "cargo-deny", "--locked"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.create-iso]
dependencies = ["build"]
condition = { files_modified = { input = ["target/i686-unknown-none/release/glos"], output = ["glos.iso"] } }
script_runner = "@duckscript"
script = '''
mkdir iso/boot/grub
cp target/i686-unknown-none/release/glos iso/boot/glos
writefile iso/boot/grub/grub.cfg "set timeout=0\nset default=0\nmenuentry \"glOS\" {\nmultiboot2 /boot/glos\nboot\n}"
exec grub-mkrescue -o glos.iso iso
rm -r iso
'''

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.run]
dependencies = ["create-iso"]
command = "qemu-system-i386"
args = ["-cdrom", "glos.iso"]

[tasks.debug]
run_task = [
    { name = "clean", condition = { files_modified = { input = ["link.ld"], output = ["glos.iso"] } } },
    { name = "run" },
]

[tasks.check]
command = "cargo"
args = ["deny", "check"]
